version: '3.8'

services:
  nbastats-db:
    image: "postgres:9.6-alpine"
    container_name: nbastats-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: $DB_PORT
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nbastats -d nbastats" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nbastats-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nbastats-app
    # volumes:
    #   - server:/app/backend
    ports:
      - 3001:8080
    links:
      - nbastats-db
    depends_on:
      nbastats-db:
        condition: service_healthy
    restart: on-failure


# volumes:
#   server: