version: '3.8'

services:
  nbastats-db:
    image: "postgres:9.6-alpine"
    container_name: nbastats-db
    # volumes:
    #   - nbastats-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "nbastats"
      POSTGRES_USER: "nbastats"
      POSTGRES_PASSWORD: "nbastats"
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nbastats -d nbastats" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nbastats-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nbastats-app
    ports:
      - 3001:8080
    links:
      - nbastats-db
    depends_on:
      nbastats-db:
        condition: service_healthy
    restart: on-failure
