FROM python:3.11-slim-bookworm

ENV ENV=dev
ENV PORT ""
ENV TZ=America/New_York

WORKDIR /app/backend

# install python dependencies
COPY requirements.txt /app/backend/
RUN pip install -r /app/backend/requirements.txt --no-cache-dir

# copy backend files
COPY . /app/backend/

# ENTRYPOINT [ "bash", "./app/nflstats/start_scraper.sh"]