import pandas as pd
from numpy import nan
from scrapp.core.dataframes.serializers import (
    BaseDataframeValidator,
    CharField,
    FloatField,
    IntegerField,
    StaticField,
    TransformationField,
)
from scrapp.scraper import DataframeController
from scrapp.tables import schema

from .util import extract_season_as_int_or_none, get_team_id_by_abbr_or_none


class RushingAndReceivingSplitsHTMLTableSerializer(BaseDataframeValidator):
    player_id = StaticField()
    season = TransformationField(
        int, extract_season_as_int_or_none, from_columns=["Unnamed: 0_level_0_Season"]
    )
    age = IntegerField(from_column="Unnamed: 1_level_0_Age")
    team_id = TransformationField(
        str,
        get_team_id_by_abbr_or_none,
        from_columns=["Unnamed: 2_level_0_Team"],
    )
    pos = CharField(from_column="Unnamed: 4_level_0_Pos")
    gp = IntegerField(from_column="Unnamed: 5_level_0_G")
    gs = CharField(from_column="Unnamed: 6_level_0_GS")

    rush = IntegerField(from_column="Rushing_Att")
    rush_yds = IntegerField(from_column="Rushing_Yds")
    rush_tds = IntegerField(from_column="Rushing_TD")
    rush_fds = IntegerField(from_column="Rushing_1D", default=None, null=True)
    rush_succ_perc = FloatField(from_column="Rushing_Succ%", default=None, null=True)
    rush_long = IntegerField(from_column="Rushing_Lng", default=None, null=True)
    yds_per_carry = FloatField(from_column="Rushing_Y/A", default=None, null=True)
    rush_yds_per_game = FloatField(from_column="Rushing_Y/G", default=None, null=True)
    rush_per_game = FloatField(from_column="Rushing_A/G", default=None, null=True)

    targets = IntegerField(from_column="Receiving_Tgt", default=None, null=True)
    rec = IntegerField(from_column="Receiving_Rec")
    rec_yds = IntegerField(from_column="Receiving_Yds")
    yds_per_rec = FloatField(from_column="Receiving_Y/R", default=None, null=True)
    rec_tds = IntegerField(from_column="Receiving_TD")
    rec_fds = IntegerField(from_column="Receiving_1D", default=None, null=True)
    rec_succ_perc = FloatField(from_column="Receiving_Succ%", default=None, null=True)
    rec_long = IntegerField(from_column="Receiving_Lng", default=None, null=True)
    rec_per_game = FloatField(from_column="Receiving_R/G", default=None, null=True)
    rec_yds_per_game = FloatField(from_column="Receiving_Y/G", default=None, null=True)
    catch_perc = FloatField(from_column="Receiving_Ctch%", default=None, null=True)
    yds_per_target = FloatField(from_column="Receiving_Y/Tgt", default=None, null=True)


rushing_and_receiving_splits_table = DataframeController(
    "NFLPlayerRushingAndReceivingSplits",
    RushingAndReceivingSplitsHTMLTableSerializer(),
    db_table=schema.table("nflrushingandreceivingsplits"),
)

example_data = {
    ("Unnamed: 0_level_0", "Season"): {
        0: ("1982", "/players/A/AberWa00/gamelog/1982/"),
        1: ("1983", "/players/A/AberWa00/gamelog/1983/"),
        2: ("1984", "/players/A/AberWa00/gamelog/1984/"),
        3: ("1985", "/players/A/AberWa00/gamelog/1985/"),
        4: ("1986", "/players/A/AberWa00/gamelog/1986/"),
        5: ("1987", "/players/A/AberWa00/gamelog/1987/"),
        6: ("1988", "/players/A/AberWa00/gamelog/1988/"),
        7: "7 Yrs",
        8: "17 Game Avg",
        9: nan,
        10: "PIT (6 Yrs)",
        11: "PHI (1 Yr)",
    },
    ("Unnamed: 1_level_0", "Age"): {
        0: ("23", None),
        1: ("24", None),
        2: ("25", None),
        3: ("26", None),
        4: ("27", None),
        5: ("28", None),
        6: ("29", None),
        7: "7 Yrs",
        8: "17 Game Avg",
        9: nan,
        10: "PIT (6 Yrs)",
        11: "PHI (1 Yr)",
    },
    ("Unnamed: 2_level_0", "Team"): {
        0: ("PIT", "/teams/pit/1982.htm"),
        1: ("PIT", "/teams/pit/1983.htm"),
        2: ("PIT", "/teams/pit/1984.htm"),
        3: ("PIT", "/teams/pit/1985.htm"),
        4: ("PIT", "/teams/pit/1986.htm"),
        5: ("PIT", "/teams/pit/1987.htm"),
        6: ("PHI", "/teams/phi/1988.htm"),
        7: "7 Yrs",
        8: "17 Game Avg",
        9: nan,
        10: "PIT (6 Yrs)",
        11: "PHI (1 Yr)",
    },
    ("Unnamed: 3_level_0", "Lg"): {
        0: ("NFL", "/years/1982/"),
        1: ("NFL", "/years/1983/"),
        2: ("NFL", "/years/1984/"),
        3: ("NFL", "/years/1985/"),
        4: ("NFL", "/years/1986/"),
        5: ("NFL", "/years/1987/"),
        6: ("NFL", "/years/1988/"),
        7: "7 Yrs",
        8: "17 Game Avg",
        9: nan,
        10: "PIT (6 Yrs)",
        11: "PHI (1 Yr)",
    },
    ("Unnamed: 4_level_0", "Pos"): {
        0: ("RB", None),
        1: ("RB", None),
        2: ("RB", None),
        3: ("RB", None),
        4: ("RB", None),
        5: ("RB", None),
        6: ("RB", None),
        7: nan,
        8: nan,
        9: nan,
        10: nan,
        11: nan,
    },
    ("Unnamed: 5_level_0", "G"): {
        0: ("6", None),
        1: ("15", None),
        2: ("14", None),
        3: ("16", None),
        4: ("16", None),
        5: ("12", None),
        6: ("5", None),
        7: "84",
        8: "17",
        9: nan,
        10: "79",
        11: "5",
    },
    ("Unnamed: 6_level_0", "GS"): {
        0: ("0", None),
        1: ("13", None),
        2: ("7", None),
        3: ("16", None),
        4: ("16", None),
        5: ("12", None),
        6: ("0", None),
        7: "64",
        8: "13",
        9: nan,
        10: "64",
        11: "0",
    },
    ("Rushing", "Att"): {
        0: ("21", None),
        1: ("112", None),
        2: ("145", None),
        3: ("227", None),
        4: ("214", None),
        5: ("123", None),
        6: ("5", None),
        7: "847",
        8: "171",
        9: nan,
        10: "842",
        11: "5",
    },
    ("Rushing", "Yds"): {
        0: ("100", None),
        1: ("446", None),
        2: ("610", None),
        3: ("851", None),
        4: ("877", None),
        5: ("459", None),
        6: ("14", None),
        7: "3357",
        8: "679",
        9: nan,
        10: "3343",
        11: "14",
    },
    ("Rushing", "TD"): {
        0: ("2", None),
        1: ("4", None),
        2: ("1", None),
        3: ("7", None),
        4: ("6", None),
        5: ("2", None),
        6: ("0", None),
        7: "22",
        8: "4",
        9: nan,
        10: "22",
        11: "0",
    },
    ("Rushing", "Lng"): {
        0: ("34", None),
        1: ("50", None),
        2: ("31", None),
        3: ("32", None),
        4: ("38", None),
        5: ("28", None),
        6: ("5", None),
        7: "50",
        8: "50",
        9: nan,
        10: "50",
        11: "5",
    },
    ("Rushing", "Y/A"): {
        0: ("4.8", None),
        1: ("4.0", None),
        2: ("4.2", None),
        3: ("3.7", None),
        4: ("4.1", None),
        5: ("3.7", None),
        6: ("2.8", None),
        7: "4.0",
        8: "4.0",
        9: nan,
        10: "4.0",
        11: "2.8",
    },
    ("Rushing", "Y/G"): {
        0: ("16.7", None),
        1: ("29.7", None),
        2: ("43.6", None),
        3: ("53.2", None),
        4: ("54.8", None),
        5: ("38.3", None),
        6: ("2.8", None),
        7: "40.0",
        8: "40.0",
        9: nan,
        10: "42.3",
        11: "2.8",
    },
    ("Rushing", "A/G"): {
        0: ("3.5", None),
        1: ("7.5", None),
        2: ("10.4", None),
        3: ("14.2", None),
        4: ("13.4", None),
        5: ("10.3", None),
        6: ("1.0", None),
        7: "10.1",
        8: "10.1",
        9: nan,
        10: "10.7",
        11: "1.0",
    },
    ("Receiving", "Rec"): {
        0: ("1", None),
        1: ("26", None),
        2: ("16", None),
        3: ("24", None),
        4: ("47", None),
        5: ("24", None),
        6: ("1", None),
        7: "139",
        8: "28",
        9: nan,
        10: "138",
        11: "1",
    },
    ("Receiving", "Yds"): {
        0: ("14", None),
        1: ("391", None),
        2: ("135", None),
        3: ("209", None),
        4: ("395", None),
        5: ("209", None),
        6: ("-2", None),
        7: "1351",
        8: "273",
        9: nan,
        10: "1353",
        11: "-2",
    },
    ("Receiving", "Y/R"): {
        0: ("14.0", None),
        1: ("15.0", None),
        2: ("8.4", None),
        3: ("8.7", None),
        4: ("8.4", None),
        5: ("8.7", None),
        6: ("-2.0", None),
        7: "9.7",
        8: "9.7",
        9: nan,
        10: "9.8",
        11: "-2.0",
    },
    ("Receiving", "TD"): {
        0: ("0", None),
        1: ("3", None),
        2: ("0", None),
        3: ("2", None),
        4: ("2", None),
        5: ("0", None),
        6: ("0", None),
        7: "7",
        8: "1",
        9: nan,
        10: "7",
        11: "0",
    },
    ("Receiving", "Lng"): {
        0: ("14", None),
        1: ("51", None),
        2: ("59", None),
        3: ("27", None),
        4: ("27", None),
        5: ("24", None),
        6: ("-2", None),
        7: "59",
        8: "59",
        9: nan,
        10: "59",
        11: "-2",
    },
    ("Receiving", "R/G"): {
        0: ("0.2", None),
        1: ("1.7", None),
        2: ("1.1", None),
        3: ("1.5", None),
        4: ("2.9", None),
        5: ("2.0", None),
        6: ("0.2", None),
        7: "1.7",
        8: "1.7",
        9: nan,
        10: "1.7",
        11: "0.2",
    },
    ("Receiving", "Y/G"): {
        0: ("2.3", None),
        1: ("26.1", None),
        2: ("9.6", None),
        3: ("13.1", None),
        4: ("24.7", None),
        5: ("17.4", None),
        6: ("-0.4", None),
        7: "16.1",
        8: "16.1",
        9: nan,
        10: "17.1",
        11: "-0.4",
    },
    ("Scrimmage", "Touch"): {
        0: ("22", None),
        1: ("138", None),
        2: ("161", None),
        3: ("251", None),
        4: ("261", None),
        5: ("147", None),
        6: ("6", None),
        7: "986",
        8: "200",
        9: nan,
        10: "980",
        11: "6",
    },
    ("Scrimmage", "Y/Tch"): {
        0: ("5.2", None),
        1: ("6.1", None),
        2: ("4.6", None),
        3: ("4.2", None),
        4: ("4.9", None),
        5: ("4.5", None),
        6: ("2.0", None),
        7: "4.8",
        8: "1.0",
        9: nan,
        10: "4.8",
        11: "2.0",
    },
    ("Scrimmage", "YScm"): {
        0: ("114", None),
        1: ("837", None),
        2: ("745", None),
        3: ("1060", None),
        4: ("1272", None),
        5: ("668", None),
        6: ("12", None),
        7: "4708",
        8: "953",
        9: nan,
        10: "4696",
        11: "12",
    },
    ("Scrimmage", "RRTD"): {
        0: ("2", None),
        1: ("7", None),
        2: ("1", None),
        3: ("9", None),
        4: ("8", None),
        5: ("2", None),
        6: ("0", None),
        7: "29",
        8: "6",
        9: nan,
        10: "29",
        11: "0",
    },
    ("Unnamed: 25_level_0", "Fmb"): {
        0: ("0", None),
        1: ("2", None),
        2: ("0", None),
        3: ("5", None),
        4: ("4", None),
        5: ("4", None),
        6: ("0", None),
        7: "15",
        8: "3",
        9: nan,
        10: "15",
        11: "0",
    },
    ("Unnamed: 26_level_0", "AV"): {
        0: ("1", None),
        1: ("6", None),
        2: ("6", None),
        3: ("7", None),
        4: ("10", None),
        5: ("5", None),
        6: ("0", None),
        7: "35",
        8: "7",
        9: nan,
        10: "35",
        11: "0",
    },
    ("Unnamed: 27_level_0", "Awards"): {
        0: ("", None),
        1: ("", None),
        2: ("", None),
        3: ("", None),
        4: ("", None),
        5: ("", None),
        6: ("", None),
        7: nan,
        8: nan,
        9: nan,
        10: nan,
        11: nan,
    },
}

example_df = pd.DataFrame(example_data)
