from .defensive_splits import NFLDefensiveSplitsTable
from .kick_and_punt_returns import NFLKickAndPuntReturnSplitsTable
from .offensive_line_penalties_splits import NFLOffensiveLinePenaltiesSplitsTable
from .passing_splits import NFLPassingSplitsTable
from .rushing_and_receiving import NFLRushingAndReceivingSplitsTable
